Пример 1

In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b # Быстрое сложение массивов
print(result)

[5 7 9]


Создание массива

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])

Операции с массивами

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2 # [5, 7, 9]
print(result)

[5 7 9]


Матричные операции

In [11]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2) # Матричное умножение
print(result)

[[19 22]
 [43 50]]


Статистические функции

In [16]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data) # Среднее значение
std_dev = np.std(data) # Стандартное отклонение
print(mean, std_dev)

3.0 1.4142135623730951


Поддержка векторизации 

In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2 # Быстрое поэлементное умножение
print(result)

[2 4 6 8]


Доступ к элементам массива

In [31]:
>>> import numpy as np
#Теперь создадим матрицу, с которой будем работать.
>>> m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
>>> print(m)
>>> print(m[1, 0])
>>> print(m[1, :])
>>> print(m[:, 2])
>>> print(m[1, 2:])
>>> print(m[0:2, 1])
>>> print(m[0:2, 1:3])

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]
5
[[5 6 7 8]]
[[3]
 [7]
 [5]]
[[7 8]]
[[2]
 [6]]
[[2 3]
 [6 7]]


Использование boolean массива для к ndarray 

In [34]:
>>> nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
>>> letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])
>>> b = 5 > 7
>>> print(b)

False


In [42]:
>>> mod_m = np.logical_and(m>=3, m<=7)
>>> mod_m

matrix([[False, False,  True,  True],
        [ True,  True,  True, False],
        [False, False,  True,  True]])

In [45]:
>>> nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
>>> nums[nums < 5]

array([1, 2, 3, 4])

In [47]:
>>> nums[nums < 5] = 10
>>> print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [49]:
>>> m[m > 7] = 25
>>> print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]


Допольнительные функции

In [51]:
>>> np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
>>> np.arange(5, 12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [56]:
>>> np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [58]:
>>> a = [[1, 2], [3, 4]]
>>> np.matrix(a)

matrix([[1, 2],
        [3, 4]])

In [60]:
>>> np.matrix('[1, 2; 3, 4]')

matrix([[1, 2],
        [3, 4]])

In [62]:
>>> np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
>>> np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
>>> A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
>>> A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Матрицы

In [68]:
>>> v_hor_np = np.array([1, 2])
>>> print(v_hor_np )

[1 2]


In [70]:
>>> v_hor_zeros_v1 = np.zeros((5,))
>>> print(v_hor_zeros_v1 )

[0. 0. 0. 0. 0.]


In [72]:
>>> v_hor_zeros_v2 = np.zeros((1, 5))
>>> print(v_hor_zeros_v2 )

[[0. 0. 0. 0. 0.]]


In [76]:
>>> v_hor_one_v1 = np.ones((5,))
>>> print(v_hor_one_v1)

[1. 1. 1. 1. 1.]


In [78]:
>>> v_hor_one_v2 = np.ones((1, 5))
>>> print(v_hor_one_v2)

[[1. 1. 1. 1. 1.]]


Квадратные матрицы 

In [92]:
>>> m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
>>> print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
>>> m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
>>> m_sqr_arr = np.array(m_sqr)
>>> print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [96]:
>>> m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
>>> print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
>>> m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
>>> print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Диагональная матрица

In [103]:
>>> m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
>>> m_diag_np = np.matrix(m_diag)
>>> print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [105]:
>>> diag = np.diag(m_sqr_mx)
>>> print(diag)

[1 5 9]
