# Задание 1. Создание и изменение массивов #

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте
все элементы массива на 2, а затем замените все элементы больше 10 на 0.
Выведите итоговый массив.

In [8]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr = arr * 2
arr[arr > 10] = 0
print(arr)


[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


# Задание 2. Работа с булевыми масками #

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
-1 и выведите обновленный массив.


In [14]:
import numpy as np

mass = np.random.randint(1, 101, size=20)
mass[mass % 5 == 0] = -1
print(mass)

[-1 31 -1 38 92 -1 47 -1  8 -1  9 16 97  1 -1 98 -1 -1 76 41]


# Задание 3. Объединение и разбиение массивов. #

Создайте два массива NumPy размером 1×5, заполненные случайными числами
от 0 до 50.

Объедините эти массивы в один двумерный массив (по строкам).
 
Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

Выведите все промежуточные и итоговые результаты.

In [24]:
import numpy as np

mass1 = np.random.randint(0, 51, size=5)
mass2 = np.random.randint(0, 51, size=5)

arr1, arr2

(array([13, 17, 41, 37, 47]), array([18, 33, 26, 11, 45]))

In [26]:
comb_mass = np.vstack((mass1, mass2))

comb_mass

array([[ 8, 46, 20, 11, 14],
       [45, 45, 28, 22, 28]])

In [28]:
split_mass1, split_mass2 = np.split(comb_mass, 2, axis=0)

split_mass1, split_mass2

(array([[ 8, 46, 20, 11, 14]]), array([[45, 45, 28, 22, 28]]))

# Задание 4. Генерация и работа с линейными последовательностями #

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.

Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов.

Выведите результаты.

In [30]:
import numpy as np

mass = np.linspace(-10, 10, 50)
sum_all = np.sum(mass)
sum_positive = np.sum(mass[mass > 0])
sum_negative = np.sum(mass[mass < 0])

sum_all, sum_positive, sum_negative

(7.105427357601002e-15, 127.55102040816328, -127.55102040816327)

# Задание 5. Работа с диагональными и единичными матрицами #

Создайте:

Единичную матрицу размером 4×4.

Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15,
20] (не использовать циклы).

Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [32]:
import numpy as np

identity_matrix = np.eye(4)
diagonal_matrix = np.diag([5, 10, 15, 20])
sum_identity = np.sum(identity_matrix)
sum_diagonal = np.sum(diagonal_matrix)

sum_identity, sum_diagonal, sum_identity < sum_diagonal

(4.0, 50, True)

# Задание 6: Создание и базовые операции с матрицами #

Создайте две квадратные матрицы NumPy размером 3×3, заполненные
случайными целыми числами от 1 до 20. Вычислите и выведите:

Их сумму

Их разность

Их поэлементное произведение

In [34]:
import numpy as np

mass1 = np.random.randint(1, 21, size=(3, 3))
mass2 = np.random.randint(1, 21, size=(3, 3))
sum_result = mass1 + mass2
diff_result = mass1 - mass2
multi_result = mass1 * mass2

mass1, mass2, sum_result, diff_result, multi_result

(array([[17,  3, 16],
        [ 7,  5,  2],
        [17, 13,  1]]),
 array([[11,  7, 12],
        [16,  5,  4],
        [ 8,  3,  2]]),
 array([[28, 10, 28],
        [23, 10,  6],
        [25, 16,  3]]),
 array([[ 6, -4,  4],
        [-9,  0, -2],
        [ 9, 10, -1]]),
 array([[187,  21, 192],
        [112,  25,   8],
        [136,  39,   2]]))

# Задание 7. Умножение матриц #

Создайте две матрицы NumPy:

Первую размером 2×3, заполненную случайными числами от 1 до 10.

Вторую размером 3×2, заполненную случайными числами от 1 до 10.

Выполните матричное умножение ( @ или np.dot ) и выведите результат.

In [36]:
import numpy as np

mass1 = np.random.randint(1, 11, size=(2, 3))
mass2 = np.random.randint(1, 11, size=(3, 2))
result = mass1 @ mass2

mass1, mass2, result

(array([[2, 7, 8],
        [2, 8, 4]]),
 array([[8, 2],
        [2, 7],
        [8, 3]]),
 array([[94, 77],
        [64, 72]]))

# Задание 8. Определитель и обратная матрица #

Создайте случайную квадратную матрицу 3×3. Найдите и выведите:

Определитель этой матрицы

Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)

Используйте функции np.linalg.det и np.linalg.inv .

In [38]:
import numpy as np

mass = np.random.randint(1, 11, size=(3, 3))
det = np.linalg.det(mass)

if np.isclose(det, 0):
    result = "Матрица вырождена, обратной не существует."
    inverse = None
else:
    inverse = np.linalg.inv(mass)
    result = "Обратная матрица найдена."

mass, det, result, inverse

(array([[ 7,  4,  8],
        [ 5, 10,  7],
        [ 5,  2,  3]]),
 -127.99999999999997,
 'Обратная матрица найдена.',
 array([[-0.125    , -0.03125  ,  0.40625  ],
        [-0.15625  ,  0.1484375,  0.0703125],
        [ 0.3125   , -0.046875 , -0.390625 ]]))

# Задание 9. Транспортирование и след матрицы #

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от
1 до 50. 

Выведите:

Исходную матрицу

Транспонированную матрицу

След матрицы (сумму элементов на главной диагонали)

Используйте np.trace для нахождения следа.

In [40]:
import numpy as np

mass = np.random.randint(1, 51, size=(4, 4))
transposed = mass.T
trace = np.trace(mass)

mass, transposed, trace

(array([[32,  4, 40, 10],
        [38, 25, 35, 40],
        [ 5, 14, 38, 13],
        [ 8, 48, 44, 18]]),
 array([[32, 38,  5,  8],
        [ 4, 25, 14, 48],
        [40, 35, 38, 44],
        [10, 40, 13, 18]]),
 113)

# Задание 10. Системы линейных уравнений #

Решите систему линейных уравнений вида:


\begin{cases}
2x + 3y - z = 5 \\
4x - y + 2z = 6 \\
-3x + 5y + 4z = -2
\end{cases}

Используйте матричное представление Ax = B , где A – матрица коэффициентов,
x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат.

In [42]:
import numpy as np

A = np.array([
    [2,  3, -1],
    [4, -1,  2],
    [-3, 5,  4]
])
B = np.array([5, 6, -2])
x = np.linalg.solve(A, B)

x

array([1.63963964, 0.57657658, 0.00900901])

# Задание 11. Индивидуальное #

Перераспределение бюджета. Городской бюджет распределяется между
образованием, здравоохранением и транспортом. На здравоохранение
выделяется в 1.5 раза больше, чем на транспорт, а на образование — на 20%
больше, чем на здравоохранение. Всего в бюджете 5 000 000 рублей. Сколько
денег выделено на каждую сферу?

In [44]:
import numpy as np

A = np.array([
    [-1.5, 1, 0],
    [0, -1.2, 1],
    [1, 1, 1]
])
B = np.array([0, 0, 5_000_000])
sol_linalg = np.linalg.solve(A, B)
sol_matrix = np.linalg.inv(A) @ B
sol_cramer = [np.linalg.det(np.column_stack([B if i == j else A[:, j] for j in range(3)])) / np.linalg.det(A) for i in range(3)]

sol_linalg, sol_matrix, np.array(sol_cramer)

(array([1162790.69767442, 1744186.04651163, 2093023.25581395]),
 array([1162790.69767442, 1744186.04651163, 2093023.25581395]),
 array([1162790.69767442, 1744186.04651163, 2093023.25581396]))